export const ISLOADING = "ISLOADING";
export const LOGIN_LOADING = "LOGIN_LOADING";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SEARCH_ATTENDANTS_DISPLAY = "SEARCH_ATTENDANTS_DISPLAY";
export const SEND_ATTENDANCE_DATA_SUCCESS = "SEND_ATTENDANCE_DATA_SUCCESS";
export const SEND_ATTENDANCE_DATA_ERROR = "SEND_ATTENDANCE_DATA_ERROR"; 

export const VOTING_MEETING_AGENDA_SUCCESS = "VOTING_MEETING_AGENDA_SUCCESS";
export const VOTING_MEETING_AGENDA_ERROR = "VOTING_MEETING_AGENDA_ERROR";

export const BOARD_VOTE_SUCCESS = "BOARD_VOTE_SUCCESS";
export const BOARD_VOTE_ERROR = "BOARD_VOTE_ERROR";