export const LOGIN_LOADING = "LOGIN_LOADING";
export const IS_ATTENDANT_SEARCH_LOADING = "IS_ATTENDANT_SEARCH_LOADING";
export const IS_SENDING_ATTENDANT_DATA_LOADING =
  "IS_SENDING_ATTENDANT_DATA_LOADING";
export const VOTING_MEETING_AGENDA_LOADING = "VOTING_MEETING_AGENDA_LOADING";
export const BOARD_VOTE_LOADING = "BOARD_VOTE_LOADING";
export const ADD_NEW_SHAREHOLDER_LOADING = "ADD_NEW_SHAREHOLDER_LOADING";
export const UPDATE_SHAREHOLDER_LOADING = "UPDATE_SHAREHOLDER_LOADING";
export const DELEGATE_ATTENDANCE_LOADING = "DELEGATE_ATTENDANCE_LOADING";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SEARCH_ATTENDANTS_DISPLAY = "SEARCH_ATTENDANTS_DISPLAY";
export const SEND_ATTENDANCE_DATA_SUCCESS = "SEND_ATTENDANCE_DATA_SUCCESS";
export const SEND_ATTENDANCE_DATA_ERROR = "SEND_ATTENDANCE_DATA_ERROR";
export const SEND_DELEGATE_ATTENDANCE_DATA_SUCCESS =
  "SEND_DELEGATE_ATTENDANCE_DATA_SUCCESS";
export const SEND_DELEGATE_ATTENDANCE_DATA_ERROR =
  "SEND_DELEGATE_ATTENDANCE_DATA_ERROR";

export const VOTING_MEETING_AGENDA_SUCCESS = "VOTING_MEETING_AGENDA_SUCCESS";
export const VOTING_MEETING_AGENDA_ERROR = "VOTING_MEETING_AGENDA_ERROR";

export const BOARD_VOTE_SUCCESS = "BOARD_VOTE_SUCCESS";
export const BOARD_VOTE_ERROR = "BOARD_VOTE_ERROR";

export const ADD_NEW_SHAREHOLDER_SUCCESS = "ADD_NEW_SHAREHOLDER_SUCCESS";
export const ADD_NEW_SHAREHOLDER_ERROR = "ADD_NEW_SHAREHOLDER_ERROR";

export const UPDATE_SHAREHOLDER_SUCCESS = "UPDATE_SHAREHOLDER_SUCCESS";
export const UPDATE_SHAREHOLDER_ERROR = "UPDATE_SHAREHOLDER_ERROR";
